# Generated by Django 4.1.6 on 2023-02-12 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_price_on_book_alter_book_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='datetime_sell',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
